version: '3.1'

services:

  # db:
  #   image: trivadis/nlu-db-postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: ambiversenlu
  #     POSTGRES_DB: aida_20180120_cs_de_en_es_ru_zh_v18
  #     POSTGRES_USER: ambiversenlu

  # nlu:
  #   image: trivadis/ambiverse-nlu
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080
  #   environment:
  #     AIDA_CONF: aida_20180120_cs_de_en_es_ru_zh_v18_db

  jupyter:
    image: jupyter/datascience-notebook
    volumes:
      - $PWD:/home/jovyan/work
    ports:
      - 80:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: /bin/bash -c "start.sh jupyter lab --NotebookApp.password='sha1:f4f4be5b6b4d:58e21e6a09290fb2ef096fb8b865ea6f6521e7a2'"
